//This data is generated by OPENAI
//The images are generated by Gemini AI
const organicProducts = [
  {
    id: 1,
    name: "Apples",
    price: 2.99,
    stock: 5,
    image: "apple.png",
    special: false,
  },
  {
    id: 2,
    name: "Bananas",
    price: 1.99,
    stock: 3,
    image: "banana.png",
    special: false,
  },
  {
    id: 3,
    name: "Spinach",
    price: 3.49,
    stock: 3,
    image: "spinach.png",
    special: false,
  },
  {
    id: 4,
    name: "Tomatoes",
    price: 2.79,
    stock: 10,
    image: "tomatoes.png",
    special: false,
  },
  {
    id: 5,
    name: "Carrots",
    price: 1.49,
    stock: 10,
    image: "carrot.png",
    special: false,
  },
  {
    id: 6,
    name: "Avocados",
    price: 33.99,
    stock: 120,
    image: "avocado.png",
    special: false,
  },
  {
    id: 7,
    name: "Quinoa",
    price: 5.99,
    stock: 10,
    image: "Quinoa.png",
    special: false,
  },
  {
    id: 8,
    name: "Blueberries",
    price: 6.99,
    stock: 10,
    image: "blueberries.png",
    special: false,
  },
  {
    id: 9,
    name: "Kale",
    price: 3.99,
    stock: 10,
    image: "Kale.png",
    special: false,
  },
  {
    id: 10,
    name: "Broccoli",
    price: 2.69,
    stock: 10,
    image: "broccoli.png",
    special: false,
  },
  {
    id: 11,
    name: "Organic Vegetable Seeds",
    price: 2.99,
    stock: 1,
    image: "Organic Vegetable Seeds.png",
    special: true,
  },
  {
    id: 12,
    name: "Gardening Gloves",
    price: 7.99,
    stock: 1,
    image: "Gardening Gloves.png",
    special: true,
  },
  {
    id: 13,
    name: "Pruning Shears",
    price: 12.99,
    stock: 10,
    image: "Pruning Shears.png",
    special: true,
  },
  {
    id: 14,
    name: "Hand Trowel",
    price: 6.99,
    stock: 10,
    image: "Hand Trowel.png",
    special: true,
  },
  {
    id: 15,
    name: "Seedling Trays",
    price: 4.99,
    stock: 10,
    image: "Seeding tray.png",
    special: true,
  },
];

const initProductData = () => {
  return organicProducts;
};

const getFarmProducts = () => {
  return organicProducts.filter((product) => {
    return product.special === true;
  });
};

const getAllProducxts = () => {
  return organicProducts;
};

export { initProductData, getFarmProducts };
